language: java

jdk:
  - openjdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t UO264033-learningToGrow_TFG_UO264033-db245bec-3afa-48a4-b5d7-36ee404ab9ac